<ADSWorkspace Revision="5" Version="100">
    <Workspace Name="">
        <LibraryDefs Name="lib.defs" />
        <Library Name="ads_standard_layers" />
        <Library Name="ads_schematic_layers" />
        <Library Name="empro_standard_layers" />
        <Library Name="ads_builtin" />
        <Library Name="ads_standard_layers_ic" />
        <Library Name="ads_schematic_layers_ic" />
        <Library Name="ads_schematic_ports_ic" />
        <Library Name="ads_rflib" />
        <Library Name="ads_sources" />
        <Library Name="ads_simulation" />
        <Library Name="ads_tlines" />
        <Library Name="ads_bondwires" />
        <Library Name="ads_datacmps" />
        <Library Name="ads_behavioral" />
        <Library Name="ads_textfonts" />
        <Library Name="ads_common_cmps" />
        <Library Name="ads_designs" />
        <Library Name="ads_pelib" />
        <ConfigFile Name="de_sim.cfg" />
        <ConfigFile Name="hpeesofsim.cfg" />
        <Preferences Name="layout.prf" />
        <Preferences Name="schematic.prf" />
        <Library Name="AC_lib" />
        <Log Name="netlist.log" />
        <Dataset Name="ac_sim.ds" />
        <Data_Files Name="ac_sim.ds" />
        <Data_Files Name="ac_sim_data\logFile.txt" />
        <Data_Files Name="dc_annotation\%A%C_lib_ac_sim_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\%A%C_lib_ac_sim_schematic\annotation_map.xml" />
        <Data_Display Name="ac_sim.dds" />
        <ConfigFile Name="dds.cfg" />
        <Log Name="search_history.log" />
        <Dataset Name="LPF_S_parameters.ds" />
        <Data_Files Name="LPF_S_parameters.ds" />
        <Data_Files Name="LPF_S_parameters_data\logFile.txt" />
        <Data_Display Name="LPF_S_parameters.dds" />
        <Dataset Name="LPF_S_parameters_1.ds" />
        <Data_Files Name="LPF_S_parameters_1.ds" />
        <Data_Files Name="LPF_S_parameters_1_data\logFile.txt" />
        <Data_Display Name="LPF_S_parameters_1.dds" />
        <Folder Name="Day1 A C&amp; S-Parameters Simulations">
            <Cell Name="AC_lib:ac_sim" />
            <Cell Name="AC_lib:LPF_S_parameters" />
            <Cell Name="AC_lib:LPF_S_parameters_1" />
        </Folder>
    </Workspace>
</ADSWorkspace>
